# Generated by Django 3.0.6 on 2020-05-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='Earth', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
